#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use App\Actions\MovementActions;
use App\Actions\Movements\OneStepMovement;
use App\Actions\RotationActions;
use App\Actions\Rotations\RotateLeft;
use App\Actions\Rotations\RotateRight;
use App\Plateau;
use App\Simulator;

$movementBuilder = new MovementActions([new OneStepMovement()]);
$rotateBuilder   = new RotationActions([
    new RotateLeft(),
    new RotateRight(),
]);

$plateau   = new Plateau();
$simulator = new Simulator($plateau, $movementBuilder, $rotateBuilder);

$simulator->run($argv[1]);
